# coding: utf-8

"""
    商工行政資料開放平臺 data.gcis.nat.gov.tw

    <div class=\"info_description markdown\">一、申請流程說明</div><p> 1.可於上排選單的「資料目錄」內點選 「公司登記介接」或「商業登記介接」查看，或下載經濟部商業司開放資料清單(僅含API)比對各項API，挑選出適合介接使用者之API項目。<br> 2.為確保平臺服務品質與維持系統效能，使用系統介接API之單位或個人請填寫使用告知書。<br> 3.填寫完告知書，請向計畫維運團隊遞件。聯絡信箱為：data.gcis@gmail.com。<br> 4.本平臺在收到告知信件確認資料無誤後(*註一)，會進行介接設定並發信通知告知者該介接設定已完成。<br>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response200 import InlineResponse200  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse200
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response200.InlineResponse200()  # noqa: E501
        if include_optional :
            return InlineResponse200(
                president_no = '0', 
                business_name = '0', 
                business_current_status = '0', 
                business_current_status_desc = '0', 
                agency = '0', 
                agency_desc = '0', 
                business_address = '0', 
                business_item_old = None, 
                business_seq_no = '0', 
                business_item = '0', 
                business_item_desc = '0'
            )
        else :
            return InlineResponse200(
        )

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
