# coding: utf-8

"""
    商工行政資料開放平臺 data.gcis.nat.gov.tw

    <div class=\"info_description markdown\">一、申請流程說明</div><p> 1.可於上排選單的「資料目錄」內點選 「公司登記介接」或「商業登記介接」查看，或下載經濟部商業司開放資料清單(僅含API)比對各項API，挑選出適合介接使用者之API項目。<br> 2.為確保平臺服務品質與維持系統效能，使用系統介接API之單位或個人請填寫使用告知書。<br> 3.填寫完告知書，請向計畫維運團隊遞件。聯絡信箱為：data.gcis@gmail.com。<br> 4.本平臺在收到告知信件確認資料無誤後(*註一)，會進行介接設定並發信通知告知者該介接設定已完成。<br>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "taiwan-api-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="商工行政資料開放平臺 data.gcis.nat.gov.tw",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "商工行政資料開放平臺 data.gcis.nat.gov.tw"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    &lt;div class&#x3D;\&quot;info_description markdown\&quot;&gt;一、申請流程說明&lt;/div&gt;&lt;p&gt; 1.可於上排選單的「資料目錄」內點選 「公司登記介接」或「商業登記介接」查看，或下載經濟部商業司開放資料清單(僅含API)比對各項API，挑選出適合介接使用者之API項目。&lt;br&gt; 2.為確保平臺服務品質與維持系統效能，使用系統介接API之單位或個人請填寫使用告知書。&lt;br&gt; 3.填寫完告知書，請向計畫維運團隊遞件。聯絡信箱為：data.gcis@gmail.com。&lt;br&gt; 4.本平臺在收到告知信件確認資料無誤後(*註一)，會進行介接設定並發信通知告知者該介接設定已完成。&lt;br&gt;  # noqa: E501
    """
)
