# coding: utf-8

"""
    商工行政資料開放平臺 data.gcis.nat.gov.tw

    <div class=\"info_description markdown\">一、申請流程說明</div><p> 1.可於上排選單的「資料目錄」內點選 「公司登記介接」或「商業登記介接」查看，或下載經濟部商業司開放資料清單(僅含API)比對各項API，挑選出適合介接使用者之API項目。<br> 2.為確保平臺服務品質與維持系統效能，使用系統介接API之單位或個人請填寫使用告知書。<br> 3.填寫完告知書，請向計畫維運團隊遞件。聯絡信箱為：data.gcis@gmail.com。<br> 4.本平臺在收到告知信件確認資料無誤後(*註一)，會進行介接設定並發信通知告知者該介接設定已完成。<br>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineResponse200(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'president_no': 'str',
        'business_name': 'str',
        'business_current_status': 'str',
        'business_current_status_desc': 'str',
        'agency': 'str',
        'agency_desc': 'str',
        'business_address': 'str',
        'business_item_old': 'object',
        'business_seq_no': 'str',
        'business_item': 'str',
        'business_item_desc': 'str'
    }

    attribute_map = {
        'president_no': 'President_No',
        'business_name': 'Business_Name',
        'business_current_status': 'Business_Current_Status',
        'business_current_status_desc': 'Business_Current_Status_Desc',
        'agency': 'Agency',
        'agency_desc': 'Agency_Desc',
        'business_address': 'Business_Address',
        'business_item_old': 'Business_Item_Old',
        'business_seq_no': 'Business_Seq_NO',
        'business_item': 'Business_Item',
        'business_item_desc': 'Business_Item_Desc'
    }

    def __init__(self, president_no=None, business_name=None, business_current_status=None, business_current_status_desc=None, agency=None, agency_desc=None, business_address=None, business_item_old=None, business_seq_no=None, business_item=None, business_item_desc=None, local_vars_configuration=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._president_no = None
        self._business_name = None
        self._business_current_status = None
        self._business_current_status_desc = None
        self._agency = None
        self._agency_desc = None
        self._business_address = None
        self._business_item_old = None
        self._business_seq_no = None
        self._business_item = None
        self._business_item_desc = None
        self.discriminator = None

        if president_no is not None:
            self.president_no = president_no
        if business_name is not None:
            self.business_name = business_name
        if business_current_status is not None:
            self.business_current_status = business_current_status
        if business_current_status_desc is not None:
            self.business_current_status_desc = business_current_status_desc
        if agency is not None:
            self.agency = agency
        if agency_desc is not None:
            self.agency_desc = agency_desc
        if business_address is not None:
            self.business_address = business_address
        if business_item_old is not None:
            self.business_item_old = business_item_old
        if business_seq_no is not None:
            self.business_seq_no = business_seq_no
        if business_item is not None:
            self.business_item = business_item
        if business_item_desc is not None:
            self.business_item_desc = business_item_desc

    @property
    def president_no(self):
        """Gets the president_no of this InlineResponse200.  # noqa: E501


        :return: The president_no of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._president_no

    @president_no.setter
    def president_no(self, president_no):
        """Sets the president_no of this InlineResponse200.


        :param president_no: The president_no of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._president_no = president_no

    @property
    def business_name(self):
        """Gets the business_name of this InlineResponse200.  # noqa: E501


        :return: The business_name of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_name

    @business_name.setter
    def business_name(self, business_name):
        """Sets the business_name of this InlineResponse200.


        :param business_name: The business_name of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_name = business_name

    @property
    def business_current_status(self):
        """Gets the business_current_status of this InlineResponse200.  # noqa: E501


        :return: The business_current_status of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_current_status

    @business_current_status.setter
    def business_current_status(self, business_current_status):
        """Sets the business_current_status of this InlineResponse200.


        :param business_current_status: The business_current_status of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_current_status = business_current_status

    @property
    def business_current_status_desc(self):
        """Gets the business_current_status_desc of this InlineResponse200.  # noqa: E501


        :return: The business_current_status_desc of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_current_status_desc

    @business_current_status_desc.setter
    def business_current_status_desc(self, business_current_status_desc):
        """Sets the business_current_status_desc of this InlineResponse200.


        :param business_current_status_desc: The business_current_status_desc of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_current_status_desc = business_current_status_desc

    @property
    def agency(self):
        """Gets the agency of this InlineResponse200.  # noqa: E501


        :return: The agency of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._agency

    @agency.setter
    def agency(self, agency):
        """Sets the agency of this InlineResponse200.


        :param agency: The agency of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._agency = agency

    @property
    def agency_desc(self):
        """Gets the agency_desc of this InlineResponse200.  # noqa: E501


        :return: The agency_desc of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._agency_desc

    @agency_desc.setter
    def agency_desc(self, agency_desc):
        """Sets the agency_desc of this InlineResponse200.


        :param agency_desc: The agency_desc of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._agency_desc = agency_desc

    @property
    def business_address(self):
        """Gets the business_address of this InlineResponse200.  # noqa: E501


        :return: The business_address of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_address

    @business_address.setter
    def business_address(self, business_address):
        """Sets the business_address of this InlineResponse200.


        :param business_address: The business_address of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_address = business_address

    @property
    def business_item_old(self):
        """Gets the business_item_old of this InlineResponse200.  # noqa: E501


        :return: The business_item_old of this InlineResponse200.  # noqa: E501
        :rtype: object
        """
        return self._business_item_old

    @business_item_old.setter
    def business_item_old(self, business_item_old):
        """Sets the business_item_old of this InlineResponse200.


        :param business_item_old: The business_item_old of this InlineResponse200.  # noqa: E501
        :type: object
        """

        self._business_item_old = business_item_old

    @property
    def business_seq_no(self):
        """Gets the business_seq_no of this InlineResponse200.  # noqa: E501


        :return: The business_seq_no of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_seq_no

    @business_seq_no.setter
    def business_seq_no(self, business_seq_no):
        """Sets the business_seq_no of this InlineResponse200.


        :param business_seq_no: The business_seq_no of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_seq_no = business_seq_no

    @property
    def business_item(self):
        """Gets the business_item of this InlineResponse200.  # noqa: E501


        :return: The business_item of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_item

    @business_item.setter
    def business_item(self, business_item):
        """Sets the business_item of this InlineResponse200.


        :param business_item: The business_item of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_item = business_item

    @property
    def business_item_desc(self):
        """Gets the business_item_desc of this InlineResponse200.  # noqa: E501


        :return: The business_item_desc of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._business_item_desc

    @business_item_desc.setter
    def business_item_desc(self, business_item_desc):
        """Sets the business_item_desc of this InlineResponse200.


        :param business_item_desc: The business_item_desc of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._business_item_desc = business_item_desc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse200):
            return True

        return self.to_dict() != other.to_dict()
