# coding: utf-8

"""
    商工行政資料開放平臺 data.gcis.nat.gov.tw

    <div class=\"info_description markdown\">一、申請流程說明</div><p> 1.可於上排選單的「資料目錄」內點選 「公司登記介接」或「商業登記介接」查看，或下載經濟部商業司開放資料清單(僅含API)比對各項API，挑選出適合介接使用者之API項目。<br> 2.為確保平臺服務品質與維持系統效能，使用系統介接API之單位或個人請填寫使用告知書。<br> 3.填寫完告知書，請向計畫維運團隊遞件。聯絡信箱為：data.gcis@gmail.com。<br> 4.本平臺在收到告知信件確認資料無誤後(*註一)，會進行介接設定並發信通知告知者該介接設定已完成。<br>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class DefaultApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_business_info(self, format, filter, **kwargs):  # noqa: E501
        """商業登記基本資料-應用三  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_business_info(format, filter, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str format: 指定來源格式 (required)
        :param str filter: 過濾<br>公式:President_No eq [0-9]{8}<br>說明:President_No :商業登記之下的商業統一編號。 (required)
        :param str skip: 從第n筆開始條列。請填入阿拉伯數字，預設為0，下限為0，上限為500000。
        :param str top: 每次可撈取筆數。請填入阿拉伯數字，預設為50，下限為1，上限為1000。
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: list[InlineResponse200]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_business_info_with_http_info(format, filter, **kwargs)  # noqa: E501

    def get_business_info_with_http_info(self, format, filter, **kwargs):  # noqa: E501
        """商業登記基本資料-應用三  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_business_info_with_http_info(format, filter, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str format: 指定來源格式 (required)
        :param str filter: 過濾<br>公式:President_No eq [0-9]{8}<br>說明:President_No :商業登記之下的商業統一編號。 (required)
        :param str skip: 從第n筆開始條列。請填入阿拉伯數字，預設為0，下限為0，上限為500000。
        :param str top: 每次可撈取筆數。請填入阿拉伯數字，預設為50，下限為1，上限為1000。
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(list[InlineResponse200], status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'format',
            'filter',
            'skip',
            'top'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_business_info" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'format' is set
        if self.api_client.client_side_validation and ('format' not in local_var_params or  # noqa: E501
                                                        local_var_params['format'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `format` when calling `get_business_info`")  # noqa: E501
        # verify the required parameter 'filter' is set
        if self.api_client.client_side_validation and ('filter' not in local_var_params or  # noqa: E501
                                                        local_var_params['filter'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `filter` when calling `get_business_info`")  # noqa: E501

        if self.api_client.client_side_validation and 'filter' in local_var_params and not re.search(r'President_No eq [0-9]{8}', local_var_params['filter']):  # noqa: E501
            raise ApiValueError("Invalid value for parameter `filter` when calling `get_business_info`, must conform to the pattern `/President_No eq [0-9]{8}/`")  # noqa: E501
        collection_formats = {}

        path_params = {}

        query_params = []
        if 'skip' in local_var_params and local_var_params['skip'] is not None:  # noqa: E501
            query_params.append(('$skip', local_var_params['skip']))  # noqa: E501
        if 'top' in local_var_params and local_var_params['top'] is not None:  # noqa: E501
            query_params.append(('$top', local_var_params['top']))  # noqa: E501
        if 'format' in local_var_params and local_var_params['format'] is not None:  # noqa: E501
            query_params.append(('$format', local_var_params['format']))  # noqa: E501
        if 'filter' in local_var_params and local_var_params['filter'] is not None:  # noqa: E501
            query_params.append(('$filter', local_var_params['filter']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/426D5542-5F05-43EB-83F9-F1300F14E1F1', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse200]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
